name: breast_health_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  scrolling_page_indicator: ^0.1.3
  permission_handler: ^8.2.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.23.0+1
  http: ^0.13.4
  dio: ^4.0.4
  painter: ^2.0.0
  custom_clippers: ^1.0.0
  lottie: ^1.2.2
  proste_bezier_curve: ^2.0.2
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.8
  page_view_indicators: ^2.0.0 
  material_design_icons_flutter: ^5.0.6295
  sizer: ^2.0.15
  step_progress_indicator: ^1.0.1
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  image_picker: ^0.8.4+1
  shared_preferences: ^2.0.8
  survey_kit: ^0.0.21
  conditional_questions: ^1.0.0
  textfield_datepicker: ^0.1.0
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^19.4.56
  flutter_form_builder: ^7.1.1
  # google_fonts: ^2.0.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
